### PR TITLE
fixed for layout/_partial/archive.ejs

### PR DESCRIPTION
**Pull request by ghost**
Change line 21
    <% page.each(function(item){ %>
into
    <% page.posts.each(function(item){ %>
to fix the problem that I faced for 

> Object #<Object> has no method 'each'
>     at eval (eval at <anonymous> (/Users/Jeremy/Dropbox/github/scottfengjian.github.com/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:37:523)
>     at eval (eval at <anonymous> (/Users/Jeremy/Dropbox/github/scottfengjian.github.com/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:37:1751)
>     at /Users/Jeremy/Dropbox/github/scottfengjian.github.com/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
>     at Object.exports.render (/Users/Jeremy/Dropbox/github/scottfengjian.github.com/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:293:13)
>     at /Users/Jeremy/Dropbox/github/scottfengjian.github.com/node_modules/hexo-renderer-ejs/index.js:5:14
>     at Object.exports.renderSync (/usr/local/lib/node_modules/hexo/lib/core/render.js:133:12)
>     at View.renderSync (/usr/local/lib/node_modules/hexo/lib/theme/view.js:183:28)
>     at partial (/usr/local/lib/node_modules/hexo/lib/plugins/helper/partial.js:29:17)
>     at Object.module.exports (/usr/local/lib/node_modules/hexo/lib/plugins/helper/partial.js:37:12)
>     at eval (eval at <anonymous> (/Users/Jeremy/Dropbox/github/scottfengjian.github.com/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:35)

### CODE REVIEW

**Comment by jmervine** [comment]
@philippkeller @scottfengjian @ds82, 

I'm willing to pull this over and release it, but it's been a while since I've looked at this. If you're interested, as I don't have much time to look at this these days, I can add you three as contributors to this repo. Thoughts?

J

**Comment by jmervine** [comment]
Want me to transfer ownership of this? I don’t use hexo anymore.

**Comment by philippkeller** [comment]
Hm. I just made hexo work again on a new laptop after 1.5 years of blog inactivity. I got a working version now which suffices all my needs.

What would it mean to transfer ownership of this repo to me? I don't think that your repo is ahead in commits, or is it?

**Comment by jmervine** [comment]
Pretty sure I haven’t touched it since your original PR. I’d transfer the repo, and if possible the npm as well. Then it would be up to you to merge and release this.

**Comment by jmervine** [comment]
I could also just add you as a collaborator and then you could move forward without taking ownership, but I probably won’t touch this again.

**Comment by philippkeller** [comment]
fair enough, not sure I will push this much further but at least I can bring it to working for the current hexo version ->I'd be happy to take ownership, thanks!

**Comment by jmervine** [comment]
Sounds good. I'll transfer the repo now, but to add you as an owner to npm I need your npmjs.org username.

**Comment by jmervine** [comment]
I couldn't transfer ownership due to the following error:
> philippkeller already has a repository in the hexojs/hexo-theme-light network

So I just added you as a collaborator. You should have an email inviting you.

**Comment by philippkeller** [comment]
can you try transferring ownership again? I made my repo a standalone repo now so the error you encountered should no longer happen

**Comment by jmervine** [comment]
Done. Once I have your npmjs.org user, I'll add you as an owner to the npm as well.

**Comment by philippkeller** [comment]
thanks, @jmervine! My npmjs.org user is `hansplast`

**Comment by jmervine** [comment]
@philippkeller Sorry for the delay, was traveling... can't seem to find your user...

https://www.npmjs.com/~hansplast

```
👉  🐧  ~ 👉  npm search hansplast
No match found for "hansplast"
```

**Comment by philippkeller** [comment]
sorry, I misspelled! it's `hansaplast` :blush:

**Comment by jmervine** [comment]
DOH! Just realized there is no npm for this. So you're good with ownership of the repo. Enjoy! o/

**Comment by philippkeller** [comment]
since I recently updated a *lot* on this project, and the PR is open since more than 3 years IMO it doesn't make sense to keep this PR open

**Pull request closed without merging**
